DROP TABLE TBL_MEMBER ;

CREATE TABLE tbl_member(
   member_number NUMBER,
   member_id varchar2(300),
   member_password varchar2(300),
   member_name varchar2(300),
   member_phone_number varchar2(300),
   member_age NUMBER(3),
   member_gender char(1),
   CONSTRAINT pk_member PRIMARY KEY(member_number)
);

SELECT * FROM tbl_member;

INSERT INTO tbl_member
values(seq_member.nextVal, 'abc11', 'qwer1234!', '짱구', '01012345678', 5, 'm');

DROP SEQUENCE SEQ_MEMBER;

CREATE SEQUENCE seq_member START WITH 1 INCREMENT BY 1
NOCACHE 
NOCYCLE;


SELECT * FROM TBL_MEMBER tm ;

-- tbl_board 테이블 생성
CREATE TABLE tbl_board (
    board_number NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, -- Oracle에서 AUTO_INCREMENT 대체
    board_title VARCHAR2(300),
    board_content VARCHAR2(1000),
    board_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 현재 날짜/시간 기본값
    board_read_count NUMBER DEFAULT 0, -- 기본값 0
    member_number NUMBER, -- FK로 참조되는 값
    CONSTRAINT pk_board PRIMARY KEY (board_number), -- PRIMARY KEY
    CONSTRAINT fk_board FOREIGN KEY (member_number) REFERENCES tbl_member(member_number) -- FOREIGN KEY
);

SELECT * FROM TBL_BOARD;

CREATE SEQUENCE seq_board START WITH 1 INCREMENT BY 1
NOCACHE 
NOCYCLE;


insert into tbl_board
(board_number, board_title, board_content, member_number)
values(seq_board.nextVal, '테스트 타이틀3', '테스트 글 입니다3!!!', 1);

//테스트 데이터 만들기
insert into tbl_board(board_title, board_content, member_number)
(select board_title, board_content, member_number from tbl_board);


CREATE TABLE tbl_file(
    -- 서버에 저장되는 실제 파일 명
    file_system_name VARCHAR2(300),
    -- 원본 파일 명
    file_original_name VARCHAR2(300),
    -- 게시판 번호 (FK로 참조)
    board_number NUMBER,
    CONSTRAINT pk_file PRIMARY KEY(file_system_name),
    -- 외래 키 제약 조건
    CONSTRAINT fk_file FOREIGN KEY (board_number) REFERENCES tbl_board (board_number)
);